export const comparisons = [
  ["fixtures/alpha-mvp.html", "artifacts/prince-reference"],
  ["fixtures/background-images.html", "artifacts/background-images"],
  ["fixtures/border-collapse.html", "artifacts/border-collapse"],
  ["fixtures/border-sides.html", "artifacts/border-sides"],
  ["fixtures/box-sizing.html", "artifacts/box-sizing"],
  ["fixtures/css-values.html", "artifacts/css-values"],
  ["fixtures/css-basics.html", "artifacts/css-basics"],
  ["fixtures/floats.html", "artifacts/floats"],
  ["fixtures/font-shorthand.html", "artifacts/font-shorthand"],
  ["fixtures/grid.html", "artifacts/grid"],
  ["fixtures/important-cascade.html", "artifacts/important-cascade"],
  ["fixtures/inline-block.html", "artifacts/inline-block"],
  ["fixtures/inline-whitespace.html", "artifacts/inline-whitespace"],
  ["fixtures/lists.html", "artifacts/lists"],
  ["fixtures/overflow.html", "artifacts/overflow"],
  ["fixtures/replaced-images.html", "artifacts/replaced-images"],
  ["fixtures/positioning.html", "artifacts/positioning"],
  ["fixtures/selectors.html", "artifacts/selectors"],
  ["fixtures/text-transform.html", "artifacts/text-transform"],
  ["fixtures/white-space.html", "artifacts/white-space"],
  ["fixtures/width-constraints.html", "artifacts/width-constraints"]
];
